# Generated by Django 5.0.2 on 2024-11-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSpace', '0007_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
