# Generated by Django 5.0.2 on 2024-11-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSpace', '0011_videotutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
