from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


urlpatterns = [
     path('', views.home, name='home'),
     path('register/', views.register_view, name='register'),
     path('login/', views.login_view, name='login'),
     path('about/', views.about, name='about'),
     path('contact/', views.contact, name='contact'),
     path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
     path('profile/', views.profile_view, name='profile'),
     path('upload-profile-photo/', views.upload_profile_photo, name='upload_profile_photo'),
     path('create-project/', views.create_project, name='create_project'),
     path('start-coding/<int:project_id>/', views.start_coding, name='begin_coding'),
     path('edit_project/<int:project_id>/', views.edit_project, name='edit_project'),
     path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),
     path('save-project-code/<int:project_id>/', views.save_project_code, name='save_project_code'),
     path('search/', views.search_users, name='search_users'),
     path('message/<int:user_id>/', views.message_page, name='message_page'),
     path('call/<int:user_id>/', views.call_page, name='call_page'),
     path('payment/<int:project_id>/', views.payment_page, name='payment_page'),
     path('process-payment/<int:project_id>/', views.process_payment, name='process_payment'),
     path('check-payment/<int:project_id>/', views.check_payment, name='check_payment'),
     path('ide/<int:project_id>/', views.ide_page, name='start_coding'),
     path("forum/", views.forum, name="forum"),
     path('community-forum/', views.community_forum, name='community_forum'),
     path("post-question/", views.post_question, name="post_question"),
     path("question/<int:question_id>/", views.view_question, name="view_question"),
     path("question/<int:question_id>/reply/", views.reply_question, name="reply_question"),
     path('question/<int:question_id>/like/', views.like_question, name='like_question'),
     path("reply/<int:reply_id>/like/", views.like_reply, name="like_reply"),
     path("upload-notes/", views.upload_notes, name="upload_notes"),
     path('upload-video/', views.upload_video, name='upload_video'),
     path('approve-video/<int:video_id>/', views.approve_video, name='approve_video'),
     path('administrator/', views.administrator_dashboard, name='administrator_dashboard'),
     path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
     path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
     path('delete-project/<int:project_id>/', views.delete_project, name='delete_project'),
     path('edit-project/<int:project_id>/', views.edit_project, name='edit_project'),
     path('approve-video/<int:video_id>/', views.approve_video, name='approve_video'),
     path('delete-video/<int:video_id>/', views.delete_video, name='delete_video'),
     path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
     path('edit_project/<int:project_id>/', views.edit_project, name='edit_project'),
     path('category/<slug:category_slug>/', views.category_view, name='category_view'),
     path('check-pay/', views.check_pay, name='check_pay'),
     path('execute_code/', views.execute_code, name='execute_code'),
     path('save_file/', views.save_file, name='save_file'),
     path('run_code/', views.run_code, name='run_code'),
     path('project_files/', views.project_files, name='project_files'),
     path('project_files/<int:project_id>/', views.load_file, name='load_files'),
     path('mpesa/callback/', views.mpesa_callback, name='mpesa_callback'),
     path("add_goal/", views.add_goal, name="add_goal"),
]